### ISSUE TITLE
Custom IP

### ISSUE THREAD

**Issue by BernardoGiordano** [SciresM/MysteryGiftTool#2]
It seems that 192.168.1.137 is hardcoded in the program, and we actually have to fail at least once the self-test (client-side) to discover this. Not a big issue since it's easy to hardcode a custom IP, but we basically lose 10 minutes at first try and then we have to recompile a new executable every time we shut-down our router and the console gets another IP

**Comment by SciresM** [comment]
This is intentional. I mentioned it in [my release thread](https://gbatemp.net/threads/release-mystery-gift-tool.456693/): "Note: Decryption requires you to be running a copy of my crypto server on a 3ds on your local network, and for you to edit the static "crypto_ip" and "crypto_port" variables in NetworkUtils.cs to point at that 3ds.". I can add it to the README though.

Also, you should really get a static IP for your console, you can do so by manually choosing an IP in system settings.
